maint: update hooks
Signed-off-by: Ar Rakin <rakinar2@onesoftnet.eu.org>

diff --git a/maint/git-pre-receive b/maint/git-pre-receive
--- a/maint/git-pre-receive
+++ b/maint/git-pre-receive
@@ -1,9 +1,14 @@
 #!/bin/sh
 
 GPG_HOME="/srv/git/trusted-keys"
+git_lock="/tmp/freehttpd-git-push-lock"
+
+if test -f "$git_lock"; then
+	echo "Cannot accept your push at this moment. Please try again in a bit."
+	exit 1
+fi
 
 set -e
-
 read oldrev newrev refname
 
 if [ -z "$GIT_PUSH_CERT_KEY" ] || [ "$GIT_PUSH_CERT_NONCE_STATUS" != "OK" ]; then
